### ISSUE TITLE
Data definition

### ISSUE THREAD

**Issue by mcepl** [pierlauro/ffcontainers#2]
Hi,

would it be possible to add some description of the data format exported (and even more importantly expected to be imported) by the script?

**Comment by pierlauro** [comment]
Hello,
the export procedure is producing a zip archive containing 2 files:
**container.json**: json file containing a description (name, color, icon, etc...) for each container
**storage.js**: json file (even though the extension is *.js*) containing additional infos such as websites to always open in specified containers

I was unfortunately not able to find additional information on the data format of the two files, at least I found no official pointers to it.

Even though field names are really intuitive and the data model can be easily assumed, there are no warranties that it will not change in the next versions. For this reason I had decided to make a full dump of the extension's file rather than parsing its saved data.

**Comment by pierlauro** [comment]
As you pinpointed in [this comment](https://github.com/mozilla/multi-account-containers/issues/339#issuecomment-478540493), the **storage.js** file has now been replaced by the only sqlite file located at **storage/default/moz-extension+++_ADDON_ID_/idb**.

For example, considering `0-1-2-3-4-5` as uuid of the containers addon, the file would be located at **storage/default/moz-extension+++0-1-2-3-4-5/idb**.
